version: '3'
services:
  web:
    container_name: docker-django
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    working_dir: /code
    ports:
      - 8000:8000
    volumes:
      - .:/code #カレントディレクトリを/codeにマウント
    depends_on:
      - db
  db:
    container_name: docker-django-db
    image: mysql/mysql-server:8.0.13-1.1.8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: django
      MYSQL_USER: django
      MYSQL_PASSWORD: django
      MYSQL_ROOT_PASSWORD: django
      TZ: 'Asia/Tokyo'
    #codeディレクトリの/var/lib/mysqlをカレントディレクトリにマウント
    volumes:
      - ./mysql:/var/lib/mysql
